export const SET_SESSION = "SET_SESSION";
export const DELETE_SESSION = "DELETE_SESSION";

export const SET_THUMBNAIL_SIZE = "SET_THUMBNAIL_SIZE";
export const SET_SHOW_DATE = "SET_SHOW_DATE";

export const ADD_USER = "ADD_USER";
export const SET_USERS = "SET_USERS";

export const OPEN_NAVIGATION = "OPEN_NAVIGATION";
export const CLOSE_NAVIGATION = "CLOSE_NAVIGATION";
export const SET_PIN_NAVIGATION = "SET_PIN_NAVIGATION";

export const OPEN_OPTIONS_PANEL = "OPEN_OPTIONS_PANEL";
export const CLOSE_OPTIONS_PANEL = "CLOSE_OPTIONS_PANEL";

export const SET_ALBUMS = "SET_ALBUMS";
export const SORT_ALBUMS = "SORT_ALBUMS";
export const SAVE_ALBUM = "SAVE_ALBUM";
